CREATE OR REPLACE TRIGGER XYZ2
BEFORE UPDATE OR DELETE ON clientmaster
FOR EACH ROW
BEGIN
  IF RTRIM(UPPER(TO_CHAR(SYSDATE, 'day'))) = 'WEDNESDAY' THEN
    RAISE_APPLICATION_ERROR(-200011, 'Cannot perform update or delete operation');
  END IF;
END;
/
